services:
  postgres:
    image: postgres:17
    container_name: postgres-develop
    restart: always
    networks:
      - backend-develop
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db.sec:/run/secrets/postgres
      - ./createuser.pg:/docker-entrypoint-initdb.d/createuser.sql
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres
      POSTGRES_INITDB_ARGS: "--no-locale -E UTF-8 -A scram-sha-256"
      TZ: Asia/Tokyo
    healthcheck:
      test: "pg_isready -U postgres || exit 1"
      interval: 1s
      timeout: 5s
      retries: 10
  postgres-test:
    image: postgres:17
    container_name: postgres-test
    ports:
      - 127.0.0.1:15432:5432
    shm_size: 1gb
    environment:
      POSTGRES_PASSWORD: pwtest
      PGDATA: /dev/shm/pgdata
      POSTGRES_INITDB_ARGS: "--no-locale -E UTF-8 -A scram-sha-256"
      TZ: Asia/Tokyo
    healthcheck:
      test: "pg_isready -U postgres || exit 1"
      interval: 1s
      timeout: 5s
      retries: 10
  mysql:
    image: mysql:8.4
    container_name: mysql-develop
    restart: always
    networks:
      - backend-develop
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./db.sec:/run/secrets/mysql-root
      - ./createuser.mysql:/docker-entrypoint-initdb.d/createuser.sql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root
      MYSQL_DATABASE: devdb
      MYSQL_USER: devdbuser
      MYSQL_PASSWORD: pwdevdbuser
      TZ: Asia/Tokyo
    healthcheck:
      test: "MYSQL_PWD=`cat /run/secrets/mysql-root` mysql $$MYSQL_DATABASE -e 'SELECT 1' || exit 1"
      interval: 1s
      timeout: 5s
      retries: 50
  mysql-test:
    image: mysql:8.4
    container_name: mysql-test
    ports:
      - 127.0.0.1:13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pwtest
      MYSQL_DATABASE: testdb
      MYSQL_USER: testdbuser
      MYSQL_PASSWORD: pwtestdbuser
      TZ: Asia/Tokyo
    healthcheck:
      test: "MYSQL_PWD=$$MYSQL_ROOT_PASSWORD mysql $$MYSQL_DATABASE -e 'SELECT 1' || exit 1"
      interval: 1s
      timeout: 5s
      retries: 50
networks:
  backend-develop:
    name: backend-develop
