services:
  postgres:
    image: postgres
    container_name: postgres-develop
    restart: always
    networks:
      - backend-develop
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: pwdev
      POSTGRES_INITDB_ARGS: "--no-locale -E UTF-8"
      TZ: Asia/Tokyo
  postgres-test:
    image: postgres
    container_name: postgres-test
    restart: always
    ports:
      - 127.0.0.1:15432:5432
    shm_size: 1gb
    environment:
      POSTGRES_PASSWORD: pwtest
      PGDATA: /dev/shm/pgdata
      POSTGRES_INITDB_ARGS: "--no-locale -E UTF-8"
      TZ: Asia/Tokyo
networks:
  backend-develop:
    name: backend-develop
  default:
    external:
      name: backend-develop
