name: ci
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: pwtest
          POSTGRES_INITDB_ARGS: "--no-locale -E UTF-8"
          TZ: Asia/Tokyo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 15432:5432
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: pwtest
          MYSQL_DATABASE: testdb
          TZ: Asia/Tokyo
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 13306:3306

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go vet ./...
      - run: go test -coverpkg=./handler,./service,./repository ./handler
